# -*- coding: utf-8 -*-
"""Answer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12EPBpzF2AZ0W6xn7p-zZM-L6SEsUbZG3
"""

input = 5
temp = input

for i in range(input):
  temp = input
  temp-=i
  for j in range(temp):
    print(temp, end='')
    temp-=1
  print()
